
DROP SCHEMA HEALTHCARE_CLAIMS_AI_DB.CLAIMS; 
DROP SCHEMA HEALTHCARE_CLAIMS_AI_DB.APP;

DROP WAREHOUSE HEALTHCARE_CLAIMS_AI_WH;
DROP ROLE HEALTHCARE_CLAIMS_AI_ROLE;

DROP DATABASE HEALTHCARE_CLAIMS_AI_DB;
