USE ROLE ACCOUNTADMIN;

 /*============================================================
   CREATE DATABASE AND SCHEMA
   ============================================================ */ 
CREATE OR REPLACE DATABASE HEALTHCARE_CLAIMS_AI_DB;

CREATE OR REPLACE SCHEMA HEALTHCARE_CLAIMS_AI_DB.CLAIMS; 
CREATE OR REPLACE SCHEMA HEALTHCARE_CLAIMS_AI_DB.APP; 

 /*============================================================
   CREATE WAREHOUSE
   ============================================================ */ 

CREATE OR REPLACE WAREHOUSE HEALTHCARE_CLAIMS_AI_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

 /*============================================================
   CREATE PROJECT SPECIFIC ROLE
   ============================================================ */ 
CREATE ROLE IF NOT EXISTS HEALTHCARE_CLAIMS_AI_ROLE;

GRANT USAGE ON DATABASE HEALTHCARE_CLAIMS_AI_DB TO ROLE HEALTHCARE_CLAIMS_AI_ROLE;
GRANT USAGE ON SCHEMA HEALTHCARE_CLAIMS_AI_DB.CLAIMS TO ROLE HEALTHCARE_CLAIMS_AI_ROLE;

GRANT USAGE ON SCHEMA HEALTHCARE_CLAIMS_AI_DB.APP TO ROLE HEALTHCARE_CLAIMS_AI_ROLE;

GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE,
      CREATE FILE FORMAT, CREATE PROCEDURE,
      CREATE FUNCTION, CREATE STREAM, CREATE TASK
ON SCHEMA HEALTHCARE_CLAIMS_AI_DB.CLAIMS TO ROLE HEALTHCARE_CLAIMS_AI_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA HEALTHCARE_CLAIMS_AI_DB.CLAIMS TO ROLE HEALTHCARE_CLAIMS_AI_ROLE;

GRANT CREATE STREAMLIT ON SCHEMA HEALTHCARE_CLAIMS_AI_DB.APP TO ROLE HEALTHCARE_CLAIMS_AI_ROLE;


GRANT USAGE, OPERATE ON WAREHOUSE HEALTHCARE_CLAIMS_AI_WH TO ROLE HEALTHCARE_CLAIMS_AI_ROLE;

GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE HEALTHCARE_CLAIMS_AI_ROLE;


/* Replace with your actual Snowflake username. */
GRANT ROLE HEALTHCARE_CLAIMS_AI_ROLE TO USER DEEPTI;

 /*============================================================
   CREATE DOCUMENT STAGE
   ============================================================ */ 

USE ROLE HEALTHCARE_CLAIMS_AI_ROLE;
USE WAREHOUSE HEALTHCARE_CLAIMS_AI_WH;
USE DATABASE HEALTHCARE_CLAIMS_AI_DB;
USE SCHEMA CLAIMS;

CREATE OR REPLACE STAGE CLAIM_DOCUMENT_STAGE
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
    DIRECTORY = (
        ENABLE = TRUE
        AUTO_REFRESH = TRUE
    )
    COMMENT = 'Healthcare claim supporting documents';

