USE ROLE HEALTHCARE_CLAIMS_AI_ROLE;
USE WAREHOUSE HEALTHCARE_CLAIMS_AI_WH;
USE DATABASE HEALTHCARE_CLAIMS_AI_DB;
USE SCHEMA CLAIMS;


CREATE OR REPLACE STREAM HEALTHCARE_CLAIMS_AI_DB.CLAIMS.CLAIM_DOCUMENT_STAGE_STREAM
ON STAGE HEALTHCARE_CLAIMS_AI_DB.CLAIMS.CLAIM_DOCUMENT_STAGE;

--WRAPPER PROCEDURE, BECAUSE WE ARE PROCESSING FOLDERS INSTEAD OF FILES.

CREATE OR REPLACE PROCEDURE HEALTHCARE_CLAIMS_AI_DB.CLAIMS.PROCESS_NEW_CLAIMS()
RETURNS OBJECT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_FOLDERS             RESULTSET;
    V_FOLDER_PATH         VARCHAR;

    V_LOAD_RESULT         OBJECT;
    V_VALIDATION_RESULT   OBJECT;

    V_LOAD_STATUS         VARCHAR;
    V_CLAIM_ID            VARCHAR;

    V_PROCESSED_COUNT     NUMBER DEFAULT 0;
    V_FAILED_COUNT        NUMBER DEFAULT 0;

    V_LAST_ERROR          VARCHAR;

BEGIN

    /*
      DML against the stream consumes its current records.
      The temporary table has a unique name for this session.
    */
    CREATE TEMPORARY TABLE IF NOT EXISTS HEALTHCARE_CLAIMS_AI_DB.CLAIMS.NEW_FOLDERS_CURRENT_RUN
    (FOLDER_PATH VARCHAR);

    TRUNCATE TABLE HEALTHCARE_CLAIMS_AI_DB.CLAIMS.NEW_FOLDERS_CURRENT_RUN;
    INSERT INTO HEALTHCARE_CLAIMS_AI_DB.CLAIMS.NEW_FOLDERS_CURRENT_RUN
    (FOLDER_PATH)
    SELECT DISTINCT
        SPLIT_PART(S.RELATIVE_PATH, '/', 1)
    FROM
        HEALTHCARE_CLAIMS_AI_DB.CLAIMS.CLAIM_DOCUMENT_STAGE_STREAM AS S
    WHERE
        S.METADATA$ACTION = 'INSERT'
        AND POSITION('/' IN S.RELATIVE_PATH) > 0
        AND REGEXP_LIKE(
            LOWER(S.RELATIVE_PATH),
            '.*[.](pdf|png|jpg|jpeg)$'
        );


    V_FOLDERS := (SELECT FOLDER_PATH
        FROM HEALTHCARE_CLAIMS_AI_DB.CLAIMS.NEW_FOLDERS_CURRENT_RUN
    );


    FOR FOLDER_RECORD IN V_FOLDERS DO

        V_FOLDER_PATH := FOLDER_RECORD.FOLDER_PATH;
        V_LOAD_RESULT := NULL;
        V_VALIDATION_RESULT := NULL;
        V_CLAIM_ID := NULL;

        BEGIN

            CALL HEALTHCARE_CLAIMS_AI_DB.CLAIMS.LOAD_PATIENT_CLAIM_FOLDER(:V_FOLDER_PATH)
            INTO :V_LOAD_RESULT;
            
            V_LOAD_STATUS := GET(V_LOAD_RESULT, 'status')::VARCHAR;
            V_CLAIM_ID := STRIP_NULL_VALUE(GET(V_LOAD_RESULT, 'claim_id'))::VARCHAR;


            IF (V_LOAD_STATUS IN
                (
                    'SUCCESS',
                    'COMPLETED_WITH_ERRORS'
                )
                AND V_CLAIM_ID IS NOT NULL
            ) THEN

                CALL HEALTHCARE_CLAIMS_AI_DB.CLAIMS.VALIDATE_COMPLETE_CLAIM(:V_CLAIM_ID)
                INTO :V_VALIDATION_RESULT;


                V_PROCESSED_COUNT := V_PROCESSED_COUNT + 1;

            ELSE
                V_FAILED_COUNT :=
                    V_FAILED_COUNT + 1;

            END IF;


        EXCEPTION
            WHEN OTHER THEN

                V_LAST_ERROR := SQLERRM;

                V_FAILED_COUNT :=
                    V_FAILED_COUNT + 1;

        END;

    END FOR;


    RETURN OBJECT_CONSTRUCT_KEEP_NULL(
        'status',
            IFF(
                V_FAILED_COUNT = 0,
                'SUCCESS',
                'COMPLETED_WITH_ERRORS'
            ),

        'folders_processed',
            V_PROCESSED_COUNT,

        'folders_failed',
            V_FAILED_COUNT,

        'last_error',
            V_LAST_ERROR
    );

END;
$$;


CREATE OR REPLACE TASK
HEALTHCARE_CLAIMS_AI_DB.CLAIMS.PROCESS_NEW_CLAIMS_TASK
    WAREHOUSE = HEALTHCARE_CLAIMS_AI_WH
    WHEN SYSTEM$STREAM_HAS_DATA(
        'HEALTHCARE_CLAIMS_AI_DB.CLAIMS.CLAIM_DOCUMENT_STAGE_STREAM'
    )
AS
    CALL HEALTHCARE_CLAIMS_AI_DB.CLAIMS.PROCESS_NEW_CLAIMS();

ALTER TASK
HEALTHCARE_CLAIMS_AI_DB.CLAIMS.PROCESS_NEW_CLAIMS_TASK
RESUME;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE HEALTHCARE_CLAIMS_AI_ROLE;


SHOW TASKS LIKE 'PROCESS_NEW_CLAIMS_TASK'
IN SCHEMA HEALTHCARE_CLAIMS_AI_DB.CLAIMS;

SELECT SYSTEM$STREAM_HAS_DATA(
        'HEALTHCARE_CLAIMS_AI_DB.CLAIMS.CLAIM_DOCUMENT_STAGE_STREAM'
    );
SELECT
    RELATIVE_PATH,
    METADATA$ACTION
FROM HEALTHCARE_CLAIMS_AI_DB.CLAIMS.CLAIM_DOCUMENT_STAGE_STREAM
WHERE METADATA$ACTION = 'INSERT';

SELECT
    NAME,
    STATE,
    SCHEDULED_TIME,
    QUERY_START_TIME,
    COMPLETED_TIME,
    ERROR_CODE,
    ERROR_MESSAGE,
    RETURN_VALUE
FROM TABLE(
    HEALTHCARE_CLAIMS_AI_DB.INFORMATION_SCHEMA.TASK_HISTORY(
        TASK_NAME => 'PROCESS_NEW_CLAIMS_TASK',
        SCHEDULED_TIME_RANGE_START =>
            DATEADD('hour', -2, CURRENT_TIMESTAMP()),
        RESULT_LIMIT => 20
    )
)
ORDER BY SCHEDULED_TIME DESC;